### ISSUE TITLE
[FEATURE] Destructible Objects

### ISSUE THREAD

**Issue by Jantoom** [Jantoom/DECO3801-Team-Mono-2022#1]
### Description
Some walls must be destructible so that it is possible to traverse certain parts of the map. Characters themselves must also be destructible so that there are consequences for being in a bomb explosion. This functionality will allow players to have perceived objectives and consequences, satisfying part of a core mechanic in the game.

### Dependencies
* No dependencies so far, interface/component design is entity-agnostic

### Documentation
None so far

### Tasks
* [ ] Research implementing behaviour in Interfaces versus Components
* [ ] Create `Destructive` and `Destructible` assets that completes the intended behaviour
* [ ] Playtest functionality when used by a wall
* [ ] Playtest functionality when used by a character

### Members
* @Jantoom
