### ISSUE TITLE
[FEATURE] Grid System for Map Generation

### ISSUE THREAD

**Issue by Jantoom** [Jantoom/DECO3801-Team-Mono-2022#10]
### Description
The goal for this game is to have a dynamically generated map so that every playthrough is a little more unique. This is valuable for the user experience because players will retain engagement if they are not seeing the same map every time they play. To do this, a concise way of generating objects must be used. This game's map generation will use randomly-selected prefabricated terrains to incrementally grow the map.

### Dependencies
* Wall and ground prefabs

### Documentation
* None so far

### Tasks
* [ ] Create main grid map and cell classes
* [ ] Design terrain prefabs using the Unity Editor
* [ ] Write algorithm to dynamically spawn terrain using terrain prefabs

### Members
* @Jantoom 
* @gaenrique
