### ISSUE TITLE
[FEATURE] Create five prefabs to use in random terrain generation

### ISSUE THREAD

**Issue by gaenrique** [Jantoom/DECO3801-Team-Mono-2022#12]
### Description
> Multiple prefabs are needed in order to use them during the random terrain generation. These will be simply held in a list and be randomly picked during terrain generation.

### Dependencies
* #10

### Tasks
* [x] Create an empty terrain prefab
* [x] Create two prefabs and test them with random terrain generation
* [x] Create additional prefabs

### Members
* @gaenrique

**Comment by gaenrique** [comment]
Five prefabs done. Could still be tweaked to improve gameplay.
