### ISSUE TITLE
[FEATURE] Random powerup spawning

### ISSUE THREAD

**Issue by gaenrique** [Jantoom/DECO3801-Team-Mono-2022#13]
### Description
Powerups must randomly spawn while the terrain generates. This involves choosing different powerup spawn locations in each terrain prefab and adding code to the terrain generator that allows powerups to spawn.

### Dependencies
* #12 
* #10 

### Tasks
* [ ] Specify powerup spawn locations in each terrain prefab
* [ ] Spawn a random powerup in these locations as terrain generates
* [ ] Add randomness, powerups must not spawn everytime.

### Members
* @gaenrique
