### ISSUE TITLE
[FEATURE] Bomb Object

### ISSUE THREAD

**Issue by amitle6** [Jantoom/DECO3801-Team-Mono-2022#6]
### Description
Bomb that will be able to be placed by the player. The bomb explodes after a brief delay and is able to break breakable objects and damage enemy players. The bomb is a core mechanic of the game because it gives the players a tool to interact with the environment and the enemy.

### Dependencies
* [Destructible Objects](https://github.com/Jantoom/DECO3801-Team-Mono-2022/issues/1) - The bomb needs to interact with the destructible interface to do damage to objects

### Documentation
None so far

### Tasks
* [ ] Be able to place bombs down on the grid
* [ ] Bomb spawns explosion objects after a brief delay
* [ ] Explosion objects apply damage to destructible walls
* [ ] Explosion objects apply damage to players
* [ ] Play-test bomb mechanic

### Members
* @ShirinNI 
* @Jantoom
