### ISSUE TITLE
[FEATURE] Simple Main Menu

### ISSUE THREAD

**Issue by gaenrique** [Jantoom/DECO3801-Team-Mono-2022#7]
### Description
I will begin working on making a simple main menu for the game. This will not be final, I'm sure we will be able to make it look by the end of the semester if we design custom buttons and textures for the menu.

### Dependencies
* None

### Tasks
* [ ] Research how to make a main menu on Unity
* [ ] Download packages if needed
* [ ] Create game menu and link it to our MVP scene

### Members
* Enrique Gonzalez Aretos
