### ISSUE TITLE
[FEATURE] Powerups

### ISSUE THREAD

**Issue by Jantoom** [Jantoom/DECO3801-Team-Mono-2022#8]
### Description
Powerups are one way for the game's main loop to become more dynamic. The aim of these powerups is to shift the player's immediate objectives between catching up, setting traps, and hunting the other player. 

### Dependencies
* Minor dependency on grid system, no feature ticket yet

### Documentation
* None so far

### Tasks
* [x] Create base powerup script
* [x] Create "Heal" powerup
* [x] Create "Barrier" powerup
* [x] Create "Exhaust" powerup
* [x] Create "Juggernaut" powerup
* [ ] Create "Long Range" powerup
* [x] Create "Laser" powerup

### Members
* @Jantoom 
* @gaenrique

**Comment by gaenrique** [comment]
I'll work on Long Range now
